### ISSUE TITLE
Cabal Update raising ErrorParse

### ISSUE THREAD

**Issue by drewokane** [haskell/cabal#2455]
I keep getting this message when I try to update cabal on my OS X machine.

```
  % cabal update                                                                                                                                         !4679
Downloading the latest package list from hackage.haskell.org
Warning: http error: Network.Browser.request: Error raised ErrorParse "Invalidcabal: Char.intToDigit: not a digit -1
```

Cabal seemed to install fine through homebrew. I'm not sure what the issue is.

**Comment by mrdcbrush** [comment]
Can confirm I see this in current cabal 1.22 install on OS X as well. Installed Cabal via 'brew install cabal-install' command.

**Comment by 23Skidoo** [comment]
Can you paste the output of `cabal update -v3`?

**Comment by mrdcbrush** [comment]
sure thing.
```
Downloading the latest package list from hackage.haskell.org
Sending:
GET /packages/archive/00-index.tar.gz HTTP/1.1
Host: hackage.haskell.org
User-Agent: cabal-install/1.22.2.0 (osx; x86_64)

Creating new connection to hackage.haskell.org
Warning: http error: Network.Browser.request: Error raised ErrorParse "Invalidcabal: Char.intToDigit: not a digit -1
```

**Comment by ChrisPenner** [comment]
I'm having this issue (just tried today)
Did anyone find a solution?
```
Downloading the latest package list from hackage.haskell.org
Sending:
GET /packages/archive/00-index.tar.gz HTTP/1.1
Host: hackage.haskell.org
User-Agent: cabal-install/1.22.6.0 (osx; x86_64)

Creating new connection to hackage.haskell.org
Warning: http error: Network.Browser.request: Error raised ErrorParse "Invalidcabal: Char.intToDigit: not a digit -1
```

**Comment by ezyang** [comment]
Thanks for the report, what happens if you upgrade to the latest Cabal and cabal-install? You may not be able to `cabal-install` it directly, but try downloading the latest tarballs manually and building them yourselfs.

In any case, we should fix this error to be more informative.

**Comment by ChrisPenner** [comment]
Thanks for taking a look! I've been excited about Haskell, but not being able to install libraries is blocking me a lot right now.

Okay, I installed from tarballs up to latest (of cabal and cabal-install) and am unfortunately still having the same issue:
```
$ cabal update
Downloading the latest package list from hackage.haskell.org
Warning: http error: Network.Browser.request: Error raised ErrorParse "Invalidcabal: Char.intToDigit: not a digit -1
```
I found this link, it seems jml has a similar problem, but seems to have solved it outside of the chatroom unfortunately.
http://ircbrowse.net/browse/haskell?events_page=3&q=jml

Not sure if you can get anything more out of that, but it seems to be some sort of network issue, though I'm not sure how that is.

**Comment by 23Skidoo** [comment]
@ChrisPenner Try compiling and running [this test program](https://gist.github.com/23Skidoo/c8d6ab1684ea11195a04). This may be a bug in the HTTP library.

**Comment by ChrisPenner** [comment]
@23Skidoo Thanks for jumping in, here's what I get:
```
Trying to download http://hackage.haskell.org/packages/archive/00-index.tar.gz
Sending:
GET /packages/archive/00-index.tar.gz HTTP/1.1
Host: hackage.haskell.org
User-Agent: cabal-install/1.18.0.5


Creating new connection to hackage.haskell.org
http error: Network.Browser.request: Error raised ErrorParse "Invalid response: Response code test.hs: Char.intToDigit: not a digit -1
```

**Comment by 23Skidoo** [comment]
@ChrisPenner Yes, looks like this is not a cabal-install bug. Possibly something odd with your network configuration. Can you please [open a ticket on the HTTP library bug tracker](https://github.com/haskell/HTTP/issues/new)?

You can also try compiling cabal-install HEAD from source. HEAD supports downloading packages using curl/wget/PowerShell (on Windows) in addition to the HTTP library.

**Comment by BardurArantsson** [comment]
@ChrisPenner You might also want to try

```
curl -sS -v http://hackage.haskell.org/packages/archive/00-index.tar.gz > /dev/null
```

and posting the output. I suspect there's some sort of transparent HTTP proxying going on which is messing up the HTTP library header parsing. (You should probably also include the output from the above if you do file a bug for the HTTP library.)

**Comment by ChrisPenner** [comment]
Okay thanks, I'll submit a bug over there.

For reference, here's what I got:
```
curl -sS -v http://hackage.haskell.org/packages/archive/00-index.tar.gz > /dev/null
*   Trying 103.245.222.68...
* Connected to hackage.haskell.org (103.245.222.68) port 80 (#0)
> GET /packages/archive/00-index.tar.gz HTTP/1.1
> Host: hackage.haskell.org
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301Moved Permanently
< Server: nginx/1.8.0
< Content-Type: text/plain; charset=UTF-8
< Location: /packages/index.tar.gz
< Via: 1.1 varnish
< Fastly-Debug-Digest: c547f5b72740267835902a55923f5102f8888a50e8c8959289ac0af0733a219e
< Transfer-Encoding: chunked
< Accept-Ranges: bytes
< Date: Wed, 20 Jan 2016 19:06:39 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-dfw1820-DFW, cache-sjc3132-SJC
< X-Cache: MISS, MISS
< X-Cache-Hits: 0, 0
< X-Timer: S1453316799.818272,VS0,VE47
<
{ [5 bytes data]
* Connection #0 to host hackage.haskell.org left intact
```

**Comment by BardurArantsson** [comment]
Interesting. I get a space between "301" and "Moved Permanently". Everything else looks identical (well, identical *enough*).

**Comment by ChrisPenner** [comment]
Weird, I consistently don't get a space :yum:, anyways, I opened a ticket here: https://github.com/haskell/HTTP/issues/98

**Comment by 23Skidoo** [comment]
Closing in favour of haskell/HTTP#98.
