### ISSUE TITLE
cabal new-build failed - unusual path

### ISSUE THREAD

**Issue by razvan-flavius-panda** [haskell/cabal#5781]
I am using the 8.2.2 Haskell Distribution for Windows.

> cabal-install version 2.0.0.1
> compiled using version 2.0.1.1 of the Cabal library

When building https://github.com/razvan-panda/Haskell-CodeWars using cabal new-build I am getting following error:

> K:\Dropbox\Coding Challenges\Codewars\Haskell>cabal new-build
> In order, the following will be built (use -v for more details):
>  - call-stack-0.1.0 (lib) (requires build)
>  - mtl-2.2.2 (lib) (requires build)
>  - parallel-3.2.2.0 (lib) (requires build)
>  - primitive-0.6.4.0 (lib) (requires build)
>  - reflection-2.1.4 (lib) (requires build)
>  - semigroups-0.18.5 (lib) (requires build)
>  - split-0.2.3.3 (lib) (requires build)
>  - stm-2.5.0.0 (lib) (requires build)
>  - tagged-0.8.6 (lib) (requires build)
>  - text-1.2.3.1 (lib) (requires build)
>  - th-abstraction-0.2.8.0 (lib) (requires build)
>  - transformers-compat-0.6.2 (lib) +five (requires build)
>  - void-0.7.2 (lib) (requires build)
>  - vector-0.12.0.1 (lib) (requires build)
>  - StateVar-1.1.1.1 (lib) (requires build)
>  - distributive-0.6 (lib:distributive) (requires build)
>  - hashable-1.2.7.0 (lib) (requires build)
>  - transformers-base-0.4.5.2 (lib) (requires build)
>  - exceptions-0.10.0 (lib) (requires build)
>  - contravariant-1.5 (lib:contravariant) (requires build)
>  - unordered-containers-0.2.9.0 (lib) (requires build)
>  - comonad-5.0.4 (lib:comonad) (requires build)
>  - bifunctors-5.5.3 (lib) (requires build)
>  - semigroupoids-5.3.1 (lib:semigroupoids) (requires build)
>  - profunctors-5.3 (lib) (requires build)
>  - invariant-0.5.1 (lib) (requires build)
>  - free-5.1 (lib) (requires build)
>  - adjunctions-4.4 (lib) (requires build)
>  - kan-extensions-5.2 (lib:kan-extensions) (requires build)
>  - lens-4.17 (lib:lens) (requires build)
>  - CodeWars-0.1.0.0 (lib) (first run)
> Configuring parallel-3.2.2.0 (lib)...
> Configuring stm-2.5.0.0 (lib)...
> Configuring reflection-2.1.4 (lib)...
> Configuring split-0.2.3.3 (lib)...
> Configuring primitive-0.6.4.0 (lib)...
> Configuring call-stack-0.1.0 (lib)...
> Configuring mtl-2.2.2 (lib)...
> Configuring semigroups-0.18.5 (lib)...
> Building parallel-3.2.2.0 (lib)...
> Building stm-2.5.0.0 (lib)...
> Building reflection-2.1.4 (lib)...
> Building semigroups-0.18.5 (lib)...
> Building primitive-0.6.4.0 (lib)...
> Building call-stack-0.1.0 (lib)...
> Building mtl-2.2.2 (lib)...
> Building split-0.2.3.3 (lib)...
> Configuring tagged-0.8.6 (lib)...
> Configuring text-1.2.3.1 (lib)...
> Configuring th-abstraction-0.2.8.0 (lib)...
> Configuring transformers-compat-0.6.2 (lib)...
> Building tagged-0.8.6 (lib)...
> Building text-1.2.3.1 (lib)...
> Building th-abstraction-0.2.8.0 (lib)...
> Configuring void-0.7.2 (lib)...
> Building transformers-compat-0.6.2 (lib)...
> Configuring StateVar-1.1.1.1 (lib)...
> Building void-0.7.2 (lib)...
> Configuring distributive-0.6 (all, legacy fallback)...
> Building StateVar-1.1.1.1 (lib)...
> Configuring contravariant-1.5 (all, legacy fallback)...
> Configuring transformers-base-0.4.5.2 (lib)...
> Configuring exceptions-0.10.0 (lib)...
> Building contravariant-1.5 (all, legacy fallback)...
> Building transformers-base-0.4.5.2 (lib)...
> Building exceptions-0.10.0 (lib)...
> Building distributive-0.6 (all, legacy fallback)...
> 
> Failed to build th-abstraction-0.2.8.0. The failure occurred during the final
> install step.
> Build log (
> C:\Users\Razvan\AppData\Roaming\cabal\logs\ghc-8.2.2\th-abstraction-0.2.8.0-8ce192869243fe646a33c573e4d1576a97c51590.log
> ):
> Installing library in C:\Users\Razvan\AppData\Roaming\cabal\store\ghc-8.2.2\incoming\new-14288\Users\Razvan\AppData\Roaming\cabal\store\ghc-8.2.2\th-abstraction-0.2.8.0-8ce192869243fe646a33c573e4d1576a97c51590\lib
> copyFile: does not exist (The system cannot find the path specified.)e.Haskell.TH.Datatype ( src\Language\Haskell\TH\Datatype.hs, dist\build\Language\Haskell\TH\Datatype.o )
> 
> Failed to build transformers-base-0.4.5.2. The failure occurred during the
> final install step.
> Build log (
> C:\Users\Razvan\AppData\Roaming\cabal\logs\ghc-8.2.2\transformers-_-0.4.5.2-128725a1954406654282468ae108a59282f6e077.log
> ):
> Installing library in C:\Users\Razvan\AppData\Roaming\cabal\store\ghc-8.2.2\incoming\new-14288\Users\Razvan\AppData\Roaming\cabal\store\ghc-8.2.2\transformers-_-0.4.5.2-128725a1954406654282468ae108a59282f6e077\lib
> copyFile: does not exist (The system cannot find the path specified.)
> cabal: Failed to build th-abstraction-0.2.8.0 (which is required by
> CodeWars-0.1.0.0). See the build log above for details.
> Failed to build transformers-base-0.4.5.2 (which is required by
> CodeWars-0.1.0.0). See the build log above for details.

The path: `C:\Users\Razvan\AppData\Roaming\cabal\store\ghc-8.2.2\incoming\new-14288\Users\Razvan\AppData\Roaming\cabal\store\ghc-8.2.2\transformers-_-0.4.5.2-128725a1954406654282468ae108a59282f6e077\lib` seems like it could be wrong since it is repeating the part: `\Users\Razvan\AppData\Roaming\cabal\store\ghc-8.2.2\`

**Comment by 23Skidoo** [comment]
I believe that this is fixed in cabal-install 2.4.1.0 (the latest stable version).

**Comment by razvan-panda** [comment]
@23Skidoo Unfortunately I can't install cabal-install 2.4.1.0 because of the following issue:

> Microsoft Windows [Version 10.0.17134.407]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Razvan>cabal info cabal-install
> * cabal-install    (program)
>     Synopsis:      The command-line interface for Cabal and Hackage.
>     Versions available: 0.14.1, 1.22.9.0, 1.24.0.1, 1.24.0.2, 2.0.0.0, 2.0.0.1,
>                         2.2.0.0, 2.4.0.0, 2.4.1.0 (and 46 others)
>     Versions installed: [ Unknown ]
>     Homepage:      http://www.haskell.org/cabal/
>     Bug reports:   https://github.com/haskell/cabal/issues
>     Description:   The \'cabal\' command-line program simplifies the process of
>                    managing Haskell software by automating the fetching,
>                    configuration, compilation and installation of Haskell
>                    libraries and programs.
>     Category:      Distribution
>     License:       BSD3
>     Author:        Cabal Development Team (see AUTHORS file)
>     Maintainer:    Cabal Development Team <cabal-devel@haskell.org>
>     Source repo:   https://github.com/haskell/cabal/
>     Executables:   cabal
>     Flags:         native-dns, debug-expensive-assertions, debug-conflict-sets,
>                    debug-tracetree
>     Dependencies:  tracetree ==0.1.*, base >=4.8, unix >=2.5 && <2.8,
>                    Win32 ==2.*, resolv >=0.1.1 && <0.2, windns >=0.1.0 && <0.2,
>                    parsec >=3.1.13.0 && <3.2, zip-archive >=0.3.2.5 && <0.5,
>                    text >=1.2.3 && <1.3, hackage-security >=0.5.2.2 && <0.6,
>                    zlib >=0.5.3 && <0.7, time >=1.5.0.1 && <1.10,
>                    tar >=0.5.0.3 && <0.6, stm >=2.0 && <2.6, random >=1 && <1.2,
>                    process >=1.2.3.0 && <1.7, pretty ==1.1.*,
>                    network >=2.6 && <2.9, network-uri >=2.6.0.2 && <2.7,
>                    mtl >=2.0 && <2.3, HTTP >=4000.1.5 && <4000.4,
>                    hashable >=1.0 && <1.3, filepath >=1.4.0.0 && <1.5,
>                    edit-distance >=0.2.2 && <0.3, echo >=0.1.3 && <0.2,
>                    directory >=1.2.2.0 && <1.4, deepseq >=1.4.1.1 && <1.5,
>                    cryptohash-sha256 ==0.11.*, containers >=0.5.6.2 && <0.7,
>                    Cabal >=2.4.1.0 && <2.5, bytestring >=0.10.6.0 && <0.11,
>                    binary >=0.7.3 && <0.9, base16-bytestring >=0.1.1 && <0.2,
>                    base >=4.8 && <4.13, array >=0.4 && <0.6, async >=2.0 && <2.3
>     Cached:        No
> 
> 
> C:\Users\Razvan>cabal install cabal-install
> Resolving dependencies...
> Configuring mintty-0.1.2...
> Downloading random-1.1...
> Downloading tar-0.5.1.0...
> Configuring cryptohash-sha256-0.11.101.0...
> Configuring network-2.8.0.0...
> Configuring ed25519-0.0.5.0...
> Configuring text-1.2.3.1...
> Failed to install random-1.1
> Downloading windns-0.1.0.1...
> Build log ( C:\Users\Razvan\AppData\Roaming\cabal\logs\ghc-8.2.2\random-1.1-LLUGZ7T9DqQ5vN0Jbcd0We.log ):
> C:\Users\Razvan\AppData\Roaming\cabal\logs\ghc-8.2.2\random-1.1-LLUGZ7T9DqQ5vN0Jbcd0We.log: openFile: does not exist (No such file or directory)

**Comment by gbaz** [comment]
Why not just download the binary from the cabal website?

**Comment by Mistuke** [comment]
@razvan-panda The path is too long, while cabal can now handle these, GCC still cannot. I am working on something that may solve this though.  For now you can use `--store-dir` to work around this.
e.g. use `cabal --store-dir=C:\\SR new-build` and you should be able to build.

**Comment by razvan-panda** [comment]
@gbaz I installed cabal-install version 2.4.1.0 using:

    stack install cabal-install --resolver nightly-2018-12-08

Then I am getting the following error on build:

> K:\Dropbox\Coding Challenges\Codewars\Haskell>cabal new-build
> Warning: Parsing the index cache failed (Unknown encoding for constructor).
> Trying to regenerate the index cache...
> Resolving dependencies...
> Build profile: -w ghc-8.2.2 -O1
> In order, the following will be built (use -v for more details):
>  - base-orphans-0.8 (lib) (requires build)
>  - cabal-doctest-1.0.6 (lib) (requires build)
>  - call-stack-0.1.0 (lib) (requires build)
>  - mtl-2.2.2 (lib) (requires build)
>  - parallel-3.2.2.0 (lib) (requires build)
>  - primitive-0.6.4.0 (lib) (requires build)
>  - reflection-2.1.4 (lib) (requires build)
>  - semigroups-0.18.5 (lib) (requires build)
>  - split-0.2.3.3 (lib) (requires build)
>  - stm-2.5.0.0 (lib) (requires build)
>  - tagged-0.8.6 (lib) (requires build)
>  - text-1.2.3.1 (lib) (requires build)
>  - th-abstraction-0.2.8.0 (lib) (requires build)
>  - transformers-compat-0.6.2 (lib) (requires build)
>  - void-0.7.2 (lib) (requires build)
>  - vector-0.12.0.1 (lib) (requires build)
>  - StateVar-1.1.1.1 (lib) (requires build)
>  - distributive-0.6 (lib:distributive) (requires build)
>  - hashable-1.2.7.0 (lib) (requires build)
>  - transformers-base-0.4.5.2 (lib) (requires build)
>  - exceptions-0.10.0 (lib) (requires build)
>  - contravariant-1.5 (lib:contravariant) (requires build)
>  - unordered-containers-0.2.9.0 (lib) (requires build)
>  - comonad-5.0.4 (lib:comonad) (requires build)
>  - bifunctors-5.5.3 (lib) (requires build)
>  - semigroupoids-5.3.1 (lib:semigroupoids) (requires build)
>  - profunctors-5.3 (lib) (requires build)
>  - invariant-0.5.1 (lib) (requires build)
>  - free-5.1 (lib) (requires build)
>  - adjunctions-4.4 (lib) (requires build)
>  - kan-extensions-5.2 (lib:kan-extensions) (requires build)
>  - lens-4.17 (lib:lens) (requires build)
>  - CodeWars-0.1.0.0 (lib) (first run)
> Starting     cabal-doctest-1.0.6 (lib)
> Starting     base-orphans-0.8 (lib)
> Starting     semigroups-0.18.5 (lib)
> Starting     parallel-3.2.2.0 (lib)
> Starting     reflection-2.1.4 (lib)
> Starting     call-stack-0.1.0 (lib)
> Starting     primitive-0.6.4.0 (lib)
> Starting     mtl-2.2.2 (lib)
> Building     base-orphans-0.8 (lib)
> Building     mtl-2.2.2 (lib)
> Building     call-stack-0.1.0 (lib)
> Building     reflection-2.1.4 (lib)
> Building     semigroups-0.18.5 (lib)
> Building     primitive-0.6.4.0 (lib)
> Building     parallel-3.2.2.0 (lib)
> Building     cabal-doctest-1.0.6 (lib)
> Installing   semigroups-0.18.5 (lib)
> Installing   call-stack-0.1.0 (lib)
> Completed    semigroups-0.18.5 (lib)
> Starting     split-0.2.3.3 (lib)
> Completed    call-stack-0.1.0 (lib)
> Starting     stm-2.5.0.0 (lib)
> Installing   base-orphans-0.8 (lib)
> Installing   cabal-doctest-1.0.6 (lib)
> Installing   parallel-3.2.2.0 (lib)
> Completed    base-orphans-0.8 (lib)
> Starting     tagged-0.8.6 (lib)
> Completed    cabal-doctest-1.0.6 (lib)
> Starting     text-1.2.3.1 (lib)
> Completed    parallel-3.2.2.0 (lib)
> Starting     th-abstraction-0.2.8.0 (lib)
> Building     split-0.2.3.3 (lib)
> Building     stm-2.5.0.0 (lib)
> Installing   mtl-2.2.2 (lib)
> Installing   split-0.2.3.3 (lib)
> Building     tagged-0.8.6 (lib)
> Building     text-1.2.3.1 (lib)
> Building     th-abstraction-0.2.8.0 (lib)
> Completed    mtl-2.2.2 (lib)
> K:\Dropbox\Coding Challenges\Codewars\Haskell\dist-newstyle\tmp\src-19447\mtl-2.2.2\Control\Monad\Writer: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:RemoveDirectory "\\\\?\\K:\\Dropbox\\Coding Challenges\\Codewars\\Haskell\\dist-newstyle\\tmp\\src-19447\\mtl-2.2.2\\Control\\Monad\\Writer": unsatisfied constraints (The directory is not empty.)
>

**Comment by Mistuke** [comment]
Is... that Dropbox folder being actively synced? if it is it's keeping files open preventing their removals. Can you try building in an unsynced location?

**Comment by razvan-panda** [comment]
I will have to get back to you in a few days. I am sending my laptop for repairs so I won't be able to test anything any time soon.

**Comment by gbaz** [comment]
closing this as obsolete
