### ISSUE TITLE
Separate `cabal install --lib` into own command

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6481]
... e.g. `cabal env`.

People do confuse what "installing libraries" and "installing executables" means, and after answering on few issues, I think stronger that separation of commands will make UX clearer.

An alternative is to drop `--lib` flag, and teach `cabal install` to do **the** right thing every time. I don't see how it would work.

**Comment by typedrat** [comment]
The only alternative that I can see is to make it so that `cabal install` just installs every public executable or library (or foreign library if someone who actually has a project to test with wants to land that nascent patch). I don't like that, but personally I don't like the idea of adding a whole new command, either.

**Comment by phadej** [comment]
@typedrat the drawback of *install everything*, is that when you e.g. `cabal install hlint`, or `cabal install [`stylish-haskell`](https://hackage.haskell.org/package/stylish-haskell)` (which has more dependencies), all these will be in the *default* environment, therefore causing the "environment cabal hell" earlier.

That said, I guess there's a way to tell solver to solve for all components in the target package. I don't fully understand what will happen if the component sets change across versions: e.g. `yaml` package, with public libraries they might come and go: these are major version changes, but if you say `cabal install lens` it's unclear whether you want the latest version or just some version.

One way is to have `cabal install pkg` to always default to the library, and if you want executable, then you must say `cabal install pkg:exename`, which is "just" flipping the `--lib` default; but it's more explicit (and also related to https://github.com/haskell/cabal/issues/6369). One variation is to default to executable installation, if that's the only component; but that's not true for many exes (e.g. mentioned `hlint` and `stylish-haskell`, and [`cabal-install-2.2.0.0`](https://hackage.haskell.org/package/cabal-install-2.2.0.0), so `cabal install cabal-install` could not default to installing executable: there **is** a library).

This is a tough UX question.

Also I motivate `cabal env` command because then you can have subcommands, to
- list what's in the environment
- list available environments
- manage them in some other ways

One could argue that "it's just moving and editing files", but editing files is very bad UX; nor is well scriptable (c.f. `cabal user-config` for updating `~/.cabal/config`; way better than `sed`ing).

So I think that `cabal env` command is **motivated** already alone, the same way as `cabal sandbox` was "just `ghc-pkg` and pass few flags to `cabal install`"; but we need good UX for a features to be used. (Relatedly: when there would be good `cabal env` command, and `cabal store gc`, then @Mistuke's [argument](https://github.com/haskell/cabal/issues/6445#issuecomment-576024649) will become void).

**Comment by danidiaz** [comment]
One argument for keeping both behaviors under the same command is that, conceptually, both installing an executable and installing a library take something that lives safely in the store under the control of Cabal, and put it "somewhere else" not directly under Cabal control, where it can be useful to other tools but also potentially overwrite stuff that shouldn't be overwritten. That said, if we had multiple commands that did that, a sentence like "Warning: this command can alter global settings not directly under control of Cabal" could simply be added to each command's help.

One argument for splitting the command: I have the impression that some newcomers to cabal have the idea that `cabal v2-install` is used to install the dependencies required by their package (when they really should be using `cabal v2-build` instead). What's worse, `v2-install` actually tries to install libraries _somewhere_. The newcomer will get supremely confused. Having a separate command for libraries, with a name less suggestive than "install", could help with this "UX failure mode". 

Not to mention that the notion of "global package environment" is not very clear for newcomers (and it isn't very clear to me, either). In what sense is the global environment different from the Nix-like store? Are they the same thing? They are both "global", after all. A whole separate command for managing them would be a better place from which to hang documentation about the concept and its relationship to Cabal.

A further hint that the command should be split is that there are flags that only seem to affect one of the behaviors. `--install-method` is only for executables, isn't it? And `--package-env` only makes sense for libraries.

**Comment by m-renaud** [comment]
### Proposed `cabal env` API:

_Subject to bikeshedding, of course._

**Base command:** `cabal env`

**Flags:**

* `--env=<ENV>` - the environment to operate on (defaults to `default`)
* `--overwrite-existing-entries=[pkglist]` - overwrite existing entries in `<ENV>` if there is an existing version with a different hash.
    * `[pkglist]` is a comma separated list of packages names to overwrite (could accept `all` if we forbid a package named `all` on hackage /shrug)

**Sub-commands:**

* `list` - list the current environments (eg. `default`)
* `info` - information about the specified `<ENV>` (such as packages in the environment and their versions)
* `add [<packages...>]` - Add all `<packages>` to the specified `<ENV>`
* `remove <ENV> [<packages...>]` - Remove all `<packages>` from the specified `<ENV>`
* `delete --env=<ENV>` - Delete the specified `<ENV>` (`--env` must be explicitly specified)

/cc @phadej @yaxu

**Comment by phadej** [comment]
@m-renaud That is good start.

Let me comment based on `cabal-env` experience.

- `list` and `info` are good.

- Same comment about `delete` and `remove`. Specifically as these
  commands are destructive we should name environment deletion command
  somehow that you don't invoke it by accident thinking you'll
  remove a package.

  Use-case: I'd advice tidal users to use `tidal` environment for tidal
  stuff, so it's not affected by whatever else they might do.

- I'd have `cabal env remove [--env=ENV] package [package2...]

  There is no point to remove all packages from the environment,
  It is "easier" to remove whole environment.

`cabal-env` works so that it explicitly stores which packages
are asked to be added to the environment:

```
-- This is GHC environment file written by cabal-env
--
clear-package-db
global-package-db
package-db /home/ogre/.cabal/store/ghc-8.8.3/package.db
package-id base-4.13.0.0
package-id some-1.0.1-6ae17ba0ce2d6d4e39d44a0cb504c88eaeb5f1021bb9d0c11208fd57b99020d1
-- cabal-env packages: some -any
-- cabal-env plan:
-- cabal-env     /Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ActAq5dAD2IiGZT0UYdkKRpnoLIXvjSQtxNmBJAdmbOadFu
-- cabal-env     YeYvCmrbLipDaWlevQY6O15sAH0//RR1U2U3r3L3iNuCtsO4ulgbIB+DPxWzZebpraqywXx7veuy+94D
```

When new package is asked to be added to the environment
explicitly added packages are required to be there also,
(IIRC TODO: and versions are marked as preferred), so silent upgrades
don't happen. This is to prevent "rebuilding everything" after
`cabal update`.

`cabal-env` also stores a serialised version of `plan.json` data,
such that when new package is requested, and if it's in the plan already,
the operation is quick: just regenerate the environment file.
`cabal-env` doesn't expose all packages by default,
but that can be configured per environment.

**Local packages.** I understood that's what Tidal users need.
I.e. `git clone tidal && cd tidal && cabal env --env=tidal add tidal`

`cabal-env` doesn't currently support local packages, but it's not complicated
to add. As the `cabal install --lib` currently, one would need to
`sdist` the local project packages, but also copy them somewhere
in `~/.cabal/...` (folder to be configurable?) so one could have

```
-- cabal-env packages: tidal -any
-- cabal-env tarballs: tidal-1.4.9-sha256hash.tar.gz
```

we need hash to not destroy other environments.
We store the actual tarballs, so temporary `cabal.project` can be recreated
completely.

**Comment by m-renaud** [comment]
> Same comment about delete and remove. Specifically as these
> commands are destructive we should name environment deletion command
> somehow that you don't invoke it by accident thinking you'll
> remove a package

We could do something with an interactive prompt for any destructive operations:

a) Before deleting/removing, have a prompt which reiterates what the command is about to do, and prompt for y/n (see examples below)
b) Add a `-f` option which overrides the prompt.

ex.

```
$ cabal env remove some-package
You are about to remove 'some-package' from the 'default' environment, this cannot be undone.
Would you like to continue? (use -f to skip prompt)
y/n: y
```

```
$ cabal env delete-environment --env=myenv
You are about to delete the 'myenv' environment and all associated files, this cannot be undone. Would you like to continue? (use -f to skip prompt)
y/n: y
```

**Comment by m-renaud** [comment]
Another thought: for the case of overwriting locally installed packages with same name and version but different hash (local development case), we _could_ split out the overwrite case from `add` into `re-add` so you need to be explicit to overwrite a previously added package in a destructive manner:

```
$ cabal env --env=tidal add tidal
$ touch some-file-which-changes-tidal-hash
$ cabal env --env=tidal add tidal
Error: Cannot add `tidal-version` to the `tidal` environment. The environment already
contains an entry for `tidal-version` but with a different hash. This can happen if you
are developing `tidal` locally and trying to update an environment with a new version
of the package. To overwrite the existing entry in the environment file with the new
version use the following command:
  cabal env --env=tidal readd tidal
$ cabal env --env=tidal readd tidal
You are about to replace the existing entry for `tidal-version` in the `tidal` environment with a
different package, this cannot be undone.
Would you like to continue?
y/n: y
```

**Comment by fgaz** [comment]
I've been using @phadej's `cabal-env`, and it's definitely the right path imo. Here's some feedback based on my experience.

* I found it useful to create local (`.ghc.environment...`) envs (I had to move the env file) phadej/cabal-extras#17
  * I'm not sure whether the implicit environment should be `default` or a local one
* matching the `-package-env` ghc interface (like `install --lib does`) by allowing paths would be good. I was surprised when this did not work
* `--transitive` is quite useful
* some other stuff that is missing, but I assume it'll be present in cabal
  * removing a package from the env
  * unhiding a package (`add`/`install` could do it)

Other ideas:

* `cabal env` could be integrated with `write-ghc-environment-files` somehow, so that generated envs contain the plan and can be manipulated

**Comment by fgaz** [comment]
More positive feedback: https://github.com/haskell/cabal/issues/5650#issuecomment-745605389

**Comment by danidiaz** [comment]
@fgaz 

> I'm not sure whether the implicit environment should be default or a local one

Personally, I almost always use local environments, and I would perhaps expect local as the default

For example in [npm](https://docs.npmjs.com/cli/v6/commands/npm-install#description) one needs to use `--global`  or `-g` for global installs.

**Comment by danidiaz** [comment]
As a side note, [global environments currently don't work on Windows](https://gitlab.haskell.org/ghc/ghc/-/issues/19286).  I filed the bug in the GHC repo because the behavior seem to contradict GHC's own user guide.

**Comment by kindaro** [comment]
Excuse me, but how specifically is an environment better than a project with a package?

* I already know how to configure packages and projects.
* I can add all the packages I want to some _«default project»_ to the same effect as this proposed addition.
* I also know how to update and remove those packages. _(By editing the cabal file, as usual.)_
* I can set default extensions.

So, what problem is being solved here that is not already solved by projects and packages? What makes, say, `alias ghci='cabal repl --project-file ~/.cabal/top-level.project lib:top-level'` not good enough?

Presently, it takes some effort to add and remove available packages — like going there and editing the file. But I hear an exact parser is in works, and it would make it possible to emulate `cabal install --lib` by editing the specified library into the `build-depends` section of the cabal file.

**Comment by gbaz** [comment]
I think we've been through this elsewhere, but the key thing is that tools _besides cabal_ can use env files -- i.e. raw ghc or ghci, or doctest executables, or soforth.

For just having an environment for a repl, I think using what you propose is just dandy. But that's not the central or only reason to want to have working environment files.

**Comment by kindaro** [comment]
But we already have a command that is supposed to support the use cases you mention — running things in the environment of a project. It is called `cabal exec`. It [has been hinted elsewhere][1] that `cabal exec $SHELL` might be a way to get a shell in said environment, and I do not see how the command `cabal env` proposed here is different. Why is it desirable to add another command? Why not improve on what we already have?

> I think we've been through this elsewhere …

Excuse me but I do not recall.

[1]: https://github.com/tomjaguarpaw/tilapia/issues/57#issuecomment-787829195

**Comment by gbaz** [comment]
`cabal exec $SHELL` won't set a package database up "ambiently" in the environment -- it will just ensure the desired executables are in path. You may ask yourself, "ok, so how does one set a package database in the environment so we could teach cabal exec to do that?" The answer is, well you can set an environment variable in the shell that points to the a ghc environment file. Having the environment file in one or another way is essential to these sorts of work flows. The functionality in `cabal install --lib` (however it ends up being named or having its ergonomics fixed up) is intended to be a basic way to manipulate these files.

**Comment by fgaz** [comment]
> cabal exec $SHELL won't set a package database up "ambiently" in the environment

Actually it does! Exactly like this:

> you can set an environment variable in the shell that points to the a ghc environment file

Relevant lines:

https://github.com/haskell/cabal/blob/873216ff5a62730b62c25dc8d1d3acc93974e0b1/cabal-install/src/Distribution/Client/CmdExec.hs#L180-L186

example:

```
> cd someproject; cabal exec env | grep GHC_ENVIRONMENT
GHC_ENVIRONMENT=/home/fgaz/someproject/dist-newstyle/tmp/environment.-30483/.ghc.environment.x86_64-linux-8.8.4
```

P.S.: while this works, I'm still not saying it is a supported workflow or a good idea in general

**Comment by gbaz** [comment]
Thanks @fgaz ! I didn't realize that was implemented -- my understanding of the v2 work is more out of date than I realized :-)

**Comment by kindaro** [comment]
So, `cabal exec $SHELL` is your `cabal env`, working out of the box. Problem solved or am I missing something? Just need the exact printer to emulate the effect of `cabal install --lib` without editing the cabal file.

**Comment by jneira** [comment]
```
PS D:\dev\ws\haskell\issues> cabal build
No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.

PS D:\dev\ws\haskell\issues> cabal-env --install haskell-say
[   0.00004] ghc.info: ghc
[   0.01129] process.0.start: cwd=C:\TEMP ghc --info
[   0.25756] debug: GHC environment directory: C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.10.4\environments
[   0.30575] cabal.plan: ... plan input summary TODO ...
[   0.39277] process.1.start: cwd=C:\TEMP\peura-XXXX-25673f03d7cb61c2 cabal v2-build all --builddir=dist-newstyle
Resolving dependencies...
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - haskell-say-1.0.0.0 (lib) (requires build)
 - fake-package-0 (lib) (first run)
Starting     haskell-say-1.0.0.0 (lib)
Building     haskell-say-1.0.0.0 (lib)
Installing   haskell-say-1.0.0.0 (lib)
Completed    haskell-say-1.0.0.0 (lib)
Configuring library for fake-package-0..
Preprocessing library for fake-package-0..
Building library for fake-package-0..
[  71.47491] process.1.time: 71.069 seconds
[  71.69372] debug: writing environment file
[  71.79310] peu.completed: OK

PS D:\dev\ws\haskell\issues> ghc -e "HaskellSay.haskellSay \`"That is what old users of v1-install wants, no additional files nor project specific overhead, one command to install the lib and bang, use ghc(i)\`""
  ________________________________________________________
 /                                                        \
| That is what old users of v1-install wants, no           |
| additional files nor project specific overhead, one      |
| command to install the lib and bang, use ghc(i)          |
 \____       _____________________________________________/
      \    /
       \  /
        \/
  _____   _____
  \    \  \    \
   \    \  \    \
    \    \  \    \
     \    \  \    \  \-----------|
      \    \  \    \  \          |
       \    \  \    \  \---------|
       /    /  /     \
      /    /  /       \  \-------|
     /    /  /    ^    \  \      |
    /    /  /    / \    \  \ ----|
   /    /  /    /   \    \
  /____/  /____/     \____\
```

**Comment by yaxu** [comment]
Yes, I want to be able to install some libraries and use them together in ghci. I also want non-developers (end-user programmers) to be able to install and upgrade a library (in particular, the `tidal` one) without confusing breakages.

I also want to repeatedly install a library while I'm developing it. 

I don't need or want to install libraries separately from one another.

From my perspective, this is basic functionality that stopped working reliably some years ago (when, again from my perspective, the confusing and apparently redundant `--lib` flag became mandatory), and I've been fielding support requests and losing potential end-users ever since.

**Comment by kindaro** [comment]
@yaxu @jneira   Not sure if you are answering to my proposition that `cabal exec` and other existing functionality is enough to support the _«GHC calculator»_ case? Apologies if I misunderstand your messages as being addressed to me. But if you are indeed addressing me, unfortunately I am unable to understand how your comments answer to mine.

### To Alex:

I do not think your wishes can be said to be unusual after numerous testimonies [given recently in a conversation elsewhere][2]. Many people want a _«GHC calculator»_ to work great out of the box:

* Start up quickly.
* Be configurable. _(Particularly, as to what packages are available.)_
* Be simple to use.
* Run plain GHC if so asked.

Is there some specific wish that you have that is not represented in the linked thread or that I failed to mention in my summary?

[2]: https://discourse.haskell.org/t/state-of-the-cabal-q1-q2-2021/2548/52

### To Javier:

Possibly my previous messages were not clear. What I have in mind is making `cabal exec` as useful as it could be. For example, it would seem that `cabal exec --build-depends 'haskell-say' $SHELL` should do what it says on the box — it does not work but it could be made to. This would subsume the functionality of `cabal-env` [exemplified above][1].

[1]: https://github.com/haskell/cabal/issues/6481#issuecomment-854182128

Observe also that `cabal-env` creates a fake package. So, there is no _«global environment»_ to speak of anyway. This is, rather, a temporary environment, not unlike that created by `cabal repl --build-depends` or Cabal scripts. My proposition is rather that a project and a package be prepared ahead of time, in a standard location and by usual means, and then used to invoke a shell or whatever other program you like to make the dependencies of the prepared package's library to be available for. What is not to like?

**Comment by jneira** [comment]
> Possibly my previous messages were not clear. What I have in mind is making cabal exec as useful as it could be. For example, it would seem that cabal exec --build-depends 'haskell-say' $SHELL should do what it says on the box — it does not work but it could be made to. This would subsume the functionality of cabal-env exemplified above.

I am not against improving `cabal exec` and the use of  `cabal exec --build-depends 'haskell-say' $SHELL` to open a shell session with dependencies in scope.
But it actually needs a project so a .cabal file and optionally a cabal.project would be needed. It does not install missing libraries.
Even if we could make it work outside a project, the state of dependencies of ghc session would be the cabal exec params. To make it persistent you should save it as shell scripts (os specific .sh or .cmd). You would have to manage those scripts to change the session config. Or implement another way to manage dependencies persistently. :thinking:
Finally you always will need cabal as medium to get the desired ghc(i) call.

> Observe also that cabal-env creates a fake package. So, there is no «global environment» to speak of anyway.

There is indeed! the fake package is only a intermediate step to install the desired libraries in the global cabal store (if it is not already there). The main build output of cabal-env is the package environment file (`C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.10.4\environments` in the log i posted). 
`cabal-env` is totally oriented to manage those files: add, hide, show the dependencies, etc. You can have several packages environment files, and there is a global one by default (the used one in my example). ghc already knows about those files and use them out of the box. They are os agnostic.
You can have several ghc dependencies persistent sets and manage them using cabal-env commands. It already works without any project specific config or adding the config to the source file (like cabal scripts). And once cabal has done its job we can forget it and focus in ghc(i).

A demo of cabal-env maybe help to understand the use case it covers:
```
PS D:\dev\ws\haskell\issues\cabal-env-sandbox> cabal-env --name myenv --install --no-transitive text
[   0.00003] ghc.info: ghc
[   0.01258] process.0.start: cwd=C:\TEMP ghc --info
[   0.18643] debug: GHC environment directory: C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.10.4\environments
[   0.21032] process.1.start: cwd=C:\TEMP\peura-XXXX-debe574882029f6f cabal v2-build all --builddir=dist-newstyle
Resolving dependencies...
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
Preprocessing library for fake-package-0..
Building library for fake-package-0..
[  15.01863] process.1.time: 14.784 seconds
[  15.04675] debug: writing environment file
[  15.09058] peu.completed: OK
PS D:\dev\ws\haskell\issues\cabal-env-sandbox> cabal-env --name myenv --show                        [   0.00003] ghc.info: ghc
array-0.5.4.0 (hidden)
base-4.14.1.0
binary-0.8.8.0 (hidden)
bytestring-0.10.12.0 (hidden)
containers-0.6.2.1 (hidden)
deepseq-1.4.4.0 (hidden)
fake-package-0 (hidden)
ghc-boot-th-8.10.4 (hidden)
ghc-prim-0.6.1 (hidden)
integer-gmp-1.0.3.0 (hidden)
pretty-1.1.3.6 (hidden)
rts-1.0 (hidden)
template-haskell-2.16.0.0 (hidden)
text-1.2.4.1
[   0.19818] peu.completed: OK
PS D:\dev\ws\haskell\issues\cabal-env-sandbox> ghc -package-env=myenv -e "Data.Text.unpack $ Data.Text.pack  \`"Str\`""
"Str"

**Comment by fgaz** [comment]
Two additional points:

* presumably, once integrated into cabal proper, `env` won't need to create a fake project
* while environments are not reproducible (but could be made to be: cabal-env stores the plan in the file, and it could export/import it), they are _stable_. I can run `cabal update`, or add another package, and the rest of the environment will stay the same. To achieve this with a fake package, you need yet another file (cabal.freeze)

**Comment by yaxu** [comment]
Hi @kindaro, I had a good look through that thread but am afraid that I got a bit lost.

Here's a summary of my experience with the v2-commands:
  https://discourse.haskell.org/t/strange-cabal-behaviour/2178/7?u=yaxu

Here's a go at explaining my use case:

**Background**

I maintain the `tidal` library, which is popular in a certain area of the world of electronic music, but mainly used by non-programmers, I'd say a very small percentage have used Haskell for anything else that making music.

It's used through an editor plugin (e.g. for atom, vscode, emacs, vim), which is really a front end for ghci. `ghci` is started, a script is loaded (in particular, [this one](https://github.com/tidalcycles/Tidal/blob/main/BootTidal.hs)), and then people make music by sending haskell statements to ghci's stdin through the plugin. It's a rudimentary UI, but works surprisingly well.. There is a haskell summer of code project looking into replacing use of ghci with a binary providing an API that interprets code via the `hint` library, though. For now there are thousands (maybe tens of thousands?) of people making music using ghci as an interface, editing and sending code from an editor buffer, including some well known musicians.

Tidal doesn't make sound itself - it sends network messages to a synthesiser/sampler based on a different system (supercollider). So although this system is easy to learn (I've taught workshops with 8 year olds who can learn to perform music together with Haskell inside an hour), it's very difficult to install. There are install scripts, but if they go wrong, it can be very hard to fix, especially for those who haven't used a terminal window before.. Even seasoned developers can find ghc/cabal/ghcup problems very hard to fix. One list of woes can be [found in the tidal forum](https://club.tidalcycles.org/c/installation/5).

**Requirements**

Technically, for most people all they need is to start ghci with the `Sound.Tidal.Context` library loaded [as per the boot script I mentioned earlier](https://github.com/tidalcycles/Tidal/blob/main/BootTidal.hs).

That's it! There are often problems with ghcup or the chocolatey haskell install that stop them from getting that far, but where they do, `cabal update` followed by `cabal install tidal --lib` is generally how people install things and it generally works ok.

I do hear about a lot of situations where it doesn't though, and when it comes to releasing a new version of Tidal, `cabal update; cabal install tidal --lib` often doesn't work for people. When things go wrong, deleting the whole package database and starting again from scratch seems the only way out. It's a bit frustrating to spend a lot of time walking people through doing this. Often people are just very unwilling to upgrade when they've had a lot of problems installing in the first place.

Sometimes I might share a hack (a block of code to paste into ghci) that requires another library (e.g. `hosc`), and this is where I hit problems with cryptic messages about hidden packages and so on.. I guess this is what we're talking about above. 

Also I find the v2- commands just don't work while developing Tidal. More often than not, [`cabal v2-install --lib` will fail](https://pastebin.com/QDqPAGAP). So I just use the v1- commands which work fine. I'm probably using the v2- commands wrong, but the documentation assumes knowledge I don't have, so I stick with what works.

Sorry that got a bit long, but I hope it's useful in understanding where I'm coming from.

**Comment by danidiaz** [comment]
> Also I find the v2- commands just don't work while developing Tidal. More often than not, cabal v2-install --lib will fail.

@yaxu In my experience, one problem with `cabal v2-install --lib` which I hope `cabal env` will solve is that package environments are brittle (impossible?) to update.

My solution is to delete the environment file (they're just text files listing which packages should be visible, and where to find them) before calling `cabal v2-install --lib` again, perhaps with multiple packages, like `cabal v2-install --lib tidal hosc`.

For example: I was encountering problems similar to yours while calling `cabal v2-install --lib` on a local project so that it became available to `ghci` outside the project (_inside_ the project, I would simply use `cabal repl`).

I opened `ghci` outside the project to see which package environment was being picked:

    GHCi, version 8.10.4: https://www.haskell.org/ghc/  :? for help
    Loaded package environment from /home/daniel/.ghc/x86_64-linux-8.10.4/environments/default

Deleted that file, and the next `cabal v2-install --lib` worked.

**Comment by yaxu** [comment]
@danidiaz Yes I've done that often too, but rather than constantly do these workarounds, using the v1-commands is easier. Also when it comes to helping end-users with no commandline experience, I think requiring people to delete files from hidden folders due to what seem like very longstanding bugs is not a reasonable status quo.

**Comment by rd--** [comment]
Hello

I was pointed to this thread from <https://github.com/haskell/cabal-userguide/issues/1#issuecomment-862126731>

`cabal-env` is very excellent so far, it seems to be exactly the thing I've been looking for, thanks very much for this!

I have some questions.

To add a library that I have a local archive for I'm using: `cd projectDirectory ; cabal-env --local -i projectName`.

Is this the correct approach?

Is there an equivalent to: `cabal v1-install projectDirectoryOne projectDirectoryTwo...`

I think this form is nice because it helps the resolver to work out a coherent set of dependecies for a possible large set of local libraries?

I've tried various forms, ie. `cabal-env absoluteProjectDirectory` and `cabal-env file:///absoluteProjectDirectory` but with no luck so far.

Thanks again, I really hope this makes it into cabal proper!

Best,
Rohan

**Comment by jneira** [comment]
> To add a library that I have a local archive for I'm using: cd projectDirectory ; cabal-env --local -i projectName.
>
> Is this the correct approach?

I think so, just tested it and it worked for me as intended

> Is there an equivalent to: cabal v1-install projectDirectoryOne projectDirectoryTwo...

Well, it seems the tool can't handle several local packages directly. However a workaround could be create a `cabal.project` file in an arbitrary location like:

 `packages: /path/to/package1 /path/to/package2  ./../packageN`

and then you could do in that directory:

`cabal-env --local -i package1 package2 packageN`

However being able to handle several local packages seems a good addition for the final version of `cabal env`, so imo we should take it in account, Thanks for noting that difference with the v1-install workflow.

**Comment by rd--** [comment]
@jneira: That workaround works perfectly, thanks very kindly.

If replicating the `v1-` behavior is a lot of work I think that's a fine solution.

And so far `cabal-env` has worked perfectly, it's really excellent!

Best,
Rohan

**Comment by kindaro** [comment]
I have a strong feeling that stupid decisions are about to be made on the wave of populism here. Like, _«oh, this new command is so cool, let us add it right now»_ and then you have one more half-baked command to be backwards compatible with for a decade to come and even more confusion for everyone to deal with. I implore you folks to be wise and not repeat this archetypal story.

1. `v1` commands never worked. This is why we removed them. We need to design a new feature that solves the use cases of many Haskell users to come, who have no idea that `v1` ever existed. And not to dwell in the past.
2. Environments are a low level feature that no one knows how to handle. We have packages already. We also have projects. We even have global Cabal configuration and global GHC configuration. We already have enough concepts!
3. The features that are being proposed are not independent from the features we already have. That is, all the use cases we have here can be solved by a sequence of commands that we either already have or plan to have soon.

I implore you folks to take a good look at what you are doing. Take a moment to sit down with a piece of paper and write down:
* What you actually want to achieve. Not how you imagine it to work. Be declarative!
* How it can be achieved with existing features, or what is the smallest feature set to add so that it can be achieved.

My claim is that the features we need are modest:
* An ability to edit Cabal files programmatically. _(Already on the way!)_
* An ability to run `cabal exec shell` with some basic nicety properties, like _[cabal exec command] = cabal exec shell [command]_ _(surprisingly, this currently does not hold)_.
* An ability to specify a default project/package:component pointer, say via environment variables.

If you really want, you can then package some usual actions into a dedicated command. But perhaps you would not even want that.

I am not addressing every point raised in the comments above. This does not mean I overlooked them. I thought about this issue for a while and I still think my proposition solves the use cases. Please tell me if you want me to substantiate some specific points, and I shall!


Please understand: I am not a stranger to Haskell and Cabal. I care about the future of our language. I am not saying that you all should stop wanting better things for yourselves. What I am saying is — think through what you wish for!

**Comment by kindaro** [comment]
I am going to address the response of Javier to my previous message and show how his points are not enough to distinguish between my solution and the prototype of `cabal env` so far.

> > Possibly my previous messages were not clear. What I have in mind is making cabal exec as useful as it could be. For example, it would seem that cabal exec --build-depends 'haskell-say' $SHELL should do what it says on the box — it does not work but it could be made to. This would subsume the functionality of cabal-env exemplified above.
> 
> I am not against improving `cabal exec` and the use of `cabal exec --build-depends 'haskell-say' $SHELL` to open a shell session with dependencies in scope.
> But it actually needs a project so a .cabal file and optionally a cabal.project would be needed. It does not install missing libraries.
> Even if we could make it work outside a project, the state of dependencies of ghc session would be the cabal exec params. To make it persistent you should save it as shell scripts (os specific .sh or .cmd). You would have to manage those scripts to change the session config. Or implement another way to manage dependencies persistently. thinking
> Finally you always will need cabal as medium to get the desired ghc(i) call.

You need the Cabal medium anyway. You use Cabal to package those dependencies in the first place. Cabal-free work flow is not something we would discuss on the Cabal issue tracker!

Our requirement is subtler: we wish to invoke a specific `ghci` executable from a shell, such that the command and the environment are easily observable. There is also no requirement of working _«outside»_ of a project. We have a global state anyway. It is not really important how this state gets set up.

Overall, your argument goes like this: you imagine one way to do what you want with the tools I suggest, point out that it is not efficient and deem my tools useless. This is clearly not a valid argument. Of course there are inefficient ways to use tools. The question is whether there are efficient ways to use them.

> > Observe also that cabal-env creates a fake package. So, there is no «global environment» to speak of anyway.
> 
> There is indeed! the fake package is only a intermediate step to install the desired libraries in the global cabal store (if it is not already there). The main build output of cabal-env is the package environment file (`C:\Users\atrey\AppData\Roaming\ghc\x86_64-mingw32-8.10.4\environments` in the log i posted).
> `cabal-env` is totally oriented to manage those files: add, hide, show the dependencies, etc. You can have several packages environment files, and there is a global one by default (the used one in my example). ghc already knows about those files and use them out of the box. They are os agnostic.

Yes but why? Of course you can make a fake package and then run around a few miles to get what you want. Or you can simply make a fake package and get what you want. Why run around a few miles?

**Comment by yaxu** [comment]
>     1. `v1` commands never worked. This is why we removed them. We need to design a new feature that solves the use cases of many Haskell users to come, who have no idea that `v1` ever existed. And not to dwell in the past.

They worked for me, and still work.

>     2. Environments are a low level feature that no one knows how to handle. We have packages already. We also have projects. We even have global Cabal configuration and global GHC configuration. We already have enough concepts!

Agreed that the concepts of an 'environment' and a 'package' could be unified.

>     * What you actually want to achieve. Not how you imagine it to work. Be declarative!

1/ I'd like a simple set of commands for reliably using a library, or a few haskell libraries in an interpreter, and to upgrade those packages later on if new versions come out.

This use case _isn't_ for creating a new library or program, but for doing work in the interpreter.

2/ Also when developing new libraries, I'd like to install them together for trying them out in an interpreter. As I work on the libraries, I'd like to quickly re-install one or both them so I can continue trying them out.

>     * How it can be achieved with existing features, or what is the smallest feature set to add so that it can be achieved.

`cabal install <foo> --lib` seems to work for both cases, but doesn't cope with the reinstalling part, and it's unclear why the `--lib` needs appending when cabal knows it's a library (it tells me so if I forget to do the lib).

Another way to achieve 1/ is to not use ghci, and instead compile a custom interpreter based on hint, with the needed packages compiled in. A GSoC student is working on this now, it's complicated but they're making good progress with deploying to linux and windows.

To me, doing some work in an interpreter is such a basic interaction for a programming language to offer, that I think having to first understand what a 'fake package' is and work out how to make one to do that, is not reasonable. What exactly is 'fake' about this package?

**Comment by kindaro** [comment]
Alex, maybe you could try my suggestion? Only imagine that the Cabal file gets edited by itself with magical commands.

> * Go to your home.
> * Create a minimal Cabal file with a library that depends on `haskell-say`.
> * Run `cabal build`.
> * Run `cabal exec $SHELL`.
> * Enjoy!

Only instead of `haskell-say` it would be whatever other libraries you require.

Here is the Cabal file I use:
```
% cat ~/x.cabal
cabal-version: 2.4
name: x
version: 0
library
  build-depends: haskell-say
```

What I expect is that when you run `ghci` in the shell thus obtained, all the modules from those libraries will be available. Does it work?

**Comment by yaxu** [comment]
Yes that seems to work well. I couldn't get it to break by upgrading/downgrading library versions. Just one strange thing was that it seems to load the same package environment twice.
```
alex@olga:~/tmp$ cabal exec ghci
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
Loaded package environment from /home/alex/tmp/dist-newstyle/tmp/environment.-279384/.ghc.environment.x86_64-linux-8.6.5
Loaded package environment from /home/alex/tmp/dist-newstyle/tmp/environment.-279384/.ghc.environment.x86_64-linux-8.6.5
Prelude>
```

**Comment by kindaro** [comment]
I too see that the environment gets loaded twice, same as you. I have no idea why.

Please party with this set-up as hard as you can! Try that thing with `cabal.project`!

It should look somethings like this:

```
packages:
  ./x.cabal
  ~/sources/some-project/some-project.cabal
```

**Comment by Mikolaj** [comment]
How fast is `cabal exec $SHELL` and, generally, are there startup time differences? IIRC a similar idea to replace v1-install+ghci with `cabal repl` failed, because the latter was many times slower.

**Comment by kindaro** [comment]
It does not matter how fast it is, since it needs only be run once, and you can then run GHC as much as you like from inside of it. In other words, the expense of `cabal repl` is paid every time you need to get `ghci` going, but the expense of `cabal exec $SHELL` is only paid once per session.

Incidentally `cabal exec` is faster — I think because it does not check if anything needs to be built and does not construct a build plan. _(Let the expert correct me.)_ _(Also, `cabal repl --build-depends …` run outside of a project creates a new fake package every time, which my proposal circumvents by using a prepared fake package.)_ This also means that you need to run `cabal build` by hand whenever you want to get your environment updated. [I actually consider this a bug.][2]

`cabal repl` is unsuitable anyway because [some developers require][1] more immediate access to the GHC executables.

[1]: https://discourse.haskell.org/t/state-of-the-cabal-q1-q2-2021/2548/36?u=kindaro
[2]: https://github.com/tomjaguarpaw/tilapia/issues/57

**Comment by Mikolaj** [comment]
Thank you for the clarification. If the loading of package environment twice is not reported yet, we definitely should report it (even if it doesn't slow things down for `cabal exec ghci` or if `cabal exec $SHELL` is used to get a long running session).

**Comment by Mikolaj** [comment]
@kindaro: I see at the top of this ticket that `cabal env` was meant to replace `cabal install --lib` (and it turned out to also be fixing it). Do you propose to remove `cabal install --lib` and not replace it with `cabal env`?

**Comment by kindaro** [comment]
Yes. I say we should instead make the existing package and project mechanics more robust and approachable.

I say so because I find that the main stream _(not obsolete)_ features we already have are quite sufficient to cover the use cases that many believe to require `v1` commands or `cabal install --lib`. It is only those features being inconvenient and not discoverable that creates the widespread demand for new commands.

Specifically, the features I have in mind are these:
* Cabal can manage dependencies in the context of a package and a project excellently — this is its primary design goal!
* Cabal can execute any executables in `$PATH` with `cabal exec` and provides them with an appropriate environment out of the box. This means shell access.
* Cabal can run commands in the context of any local package and project from any directory, not necessarily inside said package and project.

[1]: https://discourse.haskell.org/t/state-of-the-cabal-q1-q2-2021/2548

As I said above:
> My claim is that the features we need are modest:
> * An ability to edit Cabal files programmatically. _(Already on the way!)_
> * An ability to run `cabal exec shell` with some basic nicety properties, like _[cabal exec command] = cabal exec shell [command]_ _(surprisingly, this currently does not hold)_.
> * An ability to specify a default `project/package:component` pointer, say via environment variables or via global Cabal configuration.

Why do I find adding these features more effective than adding `cabal env`?

1. These features do not introduce any new concepts, but only improve the experience we already have.
2. Even these features are not essential.

   * Any working Haskell programmer can add dependencies to components by accessing Cabal files with a text editor. It is not convenient for a person unfamiliar with the syntax of Cabal, and it is the needs of these _«lay people»_ that would be addressed by an exact printer with a command line interface.
   * `cabal exec $SHELL` mostly works. The only problem is that, when you type `cabal exec ghci`, it silently rewrites `ghci` to some specific executable, while a shell would not do that. This can be solved by manipulations of `$PATH` or we can simply disable this convenient but unprincipled rewriting and make `cabal exec` simply run whatever GHC executable it finds in `$PATH`.
   * A project, package and component may already be selected by an appropriate combination of command line arguments for those several Cabal commands which I tried it with, and whatever inconsistencies remain should be considered bugs. So, we only need a way to supply the same arguments via environment variables and global configuration — nothing new in the Linux world.

**Comment by yaxu** [comment]
I wondered what would happen if I ran `cabal build` from _inside_ a `cabal exec $SHELL`, to 'upgrade' tidal-1.7.7 to the tidal-1.7.8 work-in-progress.

I got a good number of errors like this one:
```
In file included from <command-line>:7:0: error: 

/tmp/ghc299671_0/ghc_2.h:247:0: error:
     warning: "VERSION_tidal" redefined
      247 | #define VERSION_tidal "1.7.7"
          | 
    |
247 | #define VERSION_tidal "1.7.7"
    | ^

In file included from <command-line>:7:0: error: 

/home/alex/src/tidal/dist-newstyle/build/x86_64-linux/ghc-8.6.5/tidal-1.7.8/build/autogen/cabal_macros.h:5:0: error:
     note: this is the location of the previous definition
        5 | #define VERSION_tidal "1.7.8"
          | 
  |
5 | #define VERSION_tidal "1.7.8"
  | ^
```
The build completed anyway, ending with `Loaded package environment from /home/alex/src/tidal/env/dist-newstyle/tmp/environment.-299485/.ghc.environment.x86_64-linux-8.6.5`.

Then running `ghci` allowed import of `Sound.Tidal.Context` but was for `tidal_version` 1.7.7.

Restarting the `cabal exec $SHELL` and running ghci gives this:
```
Prelude> import Sound.Tidal.Context 

<no location info>: error:
    Could not load module ‘Sound.Tidal.Context’
    It is a member of the hidden package ‘tidal-1.7.7’.
    You can run ‘:set -package tidal’ to expose it.
    (Note: this unloads all the modules in the current scope.)
```
Running `:set -package tidal` allows the module to be imported but again gave version 1.7.7.

**Comment by jneira** [comment]
@kindaro Many thanks for your thoroughtful analysis, i think you have raised valid points against `cabal env` that will help to consider what could be the path to follow. And you have proposed improvements over existing v2 commands which are nice in their own.

I think the question has been going out from purely technical criteria and has entered the user experience land which is somewhat a slippery issue, as it is related with psichology/sociology.

Lets compare your proposed workflow:

> Go to your home.
> Create a minimal Cabal file with a library that depends on haskell-say.
> Run cabal build.
> Run cabal exec $SHELL.
> Enjoy!

with cabal-env one:

> Go to your home.
> Run `cabal-env install dep1 dep2 .. depN`
> Enjoy!

and with the old v1 workflow:

> Go to your home.
> Run `cabal install dep1 dep2 .. depN`
> Enjoy!

The last ones are obviously simpler, as you already know. It puts more responsability on the build tool, so it will be more complex to implement and maintain (but we could remove the existing `cabal install --lib`). Arguably it make more complex the ui, adding a new subcommand, as you commented (although separate it makes simpler ignore it).

The key question is:

> v1 commands never worked. This is why we removed them. We need to design a new feature that solves the use cases of many Haskell users to come, who have no idea that v1 ever existed. *And not to dwell in the past*.

and

> That is, all the use cases we have here can be solved by *a sequence of commands that we either already have* or plan to have soon.

(for the record, emphasys is mine)

I think we should take care of happy users of v1 commands and offer them an alternative with *no* friction to help them in the process of v1 commands removal. And i think it can be useful for new users who wants to ignore the project centric approach which dominates entirely the v2 design. So, for me, the addition of a new subcommand worths it.

As i commented above is a issue no exclusively technical so it is hard to back them with facts. Maybe we could link v1 user comments wanting preserve their workflow or users who feel a new subcommand will disturbe them, or users who will happy adopt enhanced v2 commands. We could make a poll in different community channels.

That said another intermmediate approach could be keep `cabal-env` as a separate command but host it in the cabal repo, offer them in docs making clear the workflow it enables and include it in cabal releases.
In a possible future `cabal` could mimic the git design and make possible `cabal command` call `cabal-command` ones.

**Comment by yaxu** [comment]
Presumably the `cabal exec` functionality would be accessed via the "magic commands" that @kindaro alluded to earlier, which could look a lot like the existing non-working `cabal install --lib` and `cabal-env install` prototypes.

I don't think the suggestion is that people should make files in their home folders but that these magic commands would do something conceptually similar with this underlying functionality.

**Comment by kindaro** [comment]
## Alex:

### I tried this:

1. Put `tidal == 1.7.6` into the Cabal file.
2. Run `cabal build`.
3. Run `cabal exec $SHELL`.
4. Observe:
   ```
   % ghci
   GHCi, version 8.10.4: https://www.haskell.org/ghc/  :? for help
   Loaded package environment from /tmp/x/dist-newstyle/tmp/environment.-55751/.ghc.environment.x86_64-linux-8.10.4
   Loaded package environment from /tmp/x/dist-newstyle/tmp/environment.-55751/.ghc.environment.x86_64-linux-8.10.4
   Loaded GHCi configuration from /home/kindaro/code/dotfiles/ghci.conf
   λ import Sound.Tidal.Context
   λ tidal_version 
   "1.7.6"
   ```
5. Edit the Cabal file to make `tidal == 1.7.7`.
6. Run `cabal build`.
7. Observe:
   ```
   % ghci
   GHCi, version 8.10.4: https://www.haskell.org/ghc/  :? for help
   Loaded package environment from /tmp/x/dist-newstyle/tmp/environment.-55751/.ghc.environment.x86_64-linux-8.10.4
   Loaded package environment from /tmp/x/dist-newstyle/tmp/environment.-55751/.ghc.environment.x86_64-linux-8.10.4
   Loaded GHCi configuration from /home/kindaro/code/dotfiles/ghci.conf
   λ import Sound.Tidal.Context
   λ tidal_version
   "1.7.6"
   ```
8. Observe:
   ```
   % cat dist-newstyle/tmp/environment.-55751/.ghc.environment.x86_64-linux-8.10.4 | grep tidal
   package-id tidal-1.7.6-182459d962c228f2d673def0c1c94be61bb1139b921bd7a6f96c9d85040ca756
   ```
9. Run `cabal repl` and observe error:
   ```
   Build profile: -w ghc-8.10.4 -O1
   In order, the following will be built (use -v for more details):
    - x-0.1.0.0 (exe:x) (ephemeral targets)
   Preprocessing executable 'x' for x-0.1.0.0..
   GHCi, version 8.10.4: https://www.haskell.org/ghc/  :? for help
   Loaded package environment from /tmp/x/dist-newstyle/tmp/environment.-55751/.ghc.environment.x86_64-linux-8.10.4
   Loaded package environment from /tmp/x/dist-newstyle/tmp/environment.-55751/.ghc.environment.x86_64-linux-8.10.4
   <command line>: libHStidal-1.7.6-182459d962c228f2d673def0c1c94be61bb1139b921bd7a6f96c9d85040ca756-ghc8.10.4.so: cannot open shared object file: No such file or directory
   cabal: repl failed for exe:x from x-0.1.0.0.
   ```

So, for some reason the environment file did not get updated and also for some reason `cabal repl` is broken. The error persists outside the `cabal exec $SHELL`.

### What went wrong?

1. It is `cabal exec` that writes the environment file. So, running `cabal build` by itself has no visible effect. Could `cabal build` write the environment file? I suppose — why not?
2. Looks like `cabal repl` does not like the environment? No idea what to do here.

**Comment by kindaro** [comment]
# Javier:

The technical question is whether we want to maintain the same feature twice. As I have shown, we already have enough functional features. Is there a place for more convenience? Of course, and hopefully the way I propose can be made as convenient as any other.

Specifically:

1. The cost of initializing a package in your home is only paid once, and it may as well be initialized together with all the other things Cabal sets up on the first run.
2. This also means that you are free to ignore the very existence of said package insofar as it works, and when it breaks, you already know how to fix it since it is an ordinary Cabal package.
3. It is trivial to switch from one package to another — only swap the value of the environment variable pointing to it.

The hard thing is to add and remove dependencies magically. This is where adding a new command would be nice. Hopefully with an exact printer this would not be hard.

So, it is not like I propose to ignore all the people that want immediate access to the GHC executables or a global state. Actually, I am one of those people! Rather, I believe that we can easily transplant everyone to the setting of packages and projects without much effort, and unify everything along the way. Instead of three things to explain _(environments, packages and projects)_ there would be two _(packages and projects)_, and happily the two everyone is using anyway.

**Comment by jneira** [comment]
> Is there a place for more convenience? Of course, and hopefully the way I propose can be made as convenient as any other

If the final result offer a simple workflow which doesnt involve make users create auxiliary (project) files at all and works with a one liner like `cabal XXXX dep1 dep2 .. depN` (or two at most) i will buy it, as i am not worried by the concrete technical solution but the user experience.

> Instead of three things to explain (environments, packages and projects) there would be two (packages and projects), and happily the two everyone is using anyway.

I think you are assuming user know and want take care of project files, and it is not the case for some of them. Or they know them but want to ignore them completely for some workflows.
`cabal-env` does not require from user know nothing about environment files, packages or projects, and that is its key. You execute the command and voila! the dependencies are in scope for ghc/ghci.
Take as an example the workflow [described above](https://github.com/haskell/cabal/issues/6481#issuecomment-854218830): 

> I also want *non-developers (end-user programmers)* to be able to install and upgrade a library (in particular, the tidal one) without confusing breakages.
> I don't need or want to install libraries separately from one another.

(again emphasys is mine)

An non-developer knows nothing about .cabal, cabal.project or environment files. Maybe they dont know nothing about ghc or haskell, but you can tell them execute `xxxxx tidal` and everything works.

Another example: there are online courses focused entirely in ghc (dont forget you can use ghc as well!) and ghci. They dont want confuse or worry beginners with build tool business, but want to use useful packages out there in the course. So teachers, maybe advanced haskell developers which know how to use cabal perfectly, only want to being able to tell beginners: "execute `xxxx package1 package2` before start the lesson with ghci".

I want preserve the possibility of doing that, independently of what machinery is underneath.

**Comment by Mikolaj** [comment]
I think we all already agree it makes sense to report bugs, fix and improve the components of the `cabal exec`-focused workflow. As we do that, I hope we'd understand things better. E.g., it may turn out that environment variables in `cabal exec` are brittle (e.g., when nesting) and too implicit and using the environment files in `cabal env` is easier to maintain, explain and tweak by users, while being analogous in many other ways to what `cabal exec` does. Or we may see that `cabal exec` is simple enough and works fine and with some extra sugar it lets us replace `cabal install --lib` and also the v1- workflow comfortably. 

I totally can't tell at this point nor can I ask users for feedback about the `cabal exec` workflow in its fixed and user friendly form. I'd prefer one set of commands (polished `cabal exec` set) to two (`cabal env`, basic `cabal exec`), but not at all cost.

**Comment by kindaro** [comment]
# Javier:

All you need to support this use case is add a command that allows to edit Cabal files programmatically — or even merely to initialize packages with given dependencies. The latter can already be done with a patch to `cabal init`, since it does not require exact printing.

Essentially you like `cabal env` because it edits files for you. If this is what you want, then this is what you should ask for. It is not about the installation of libraries or the creation of environments — all of that is already handled by Cabal well enough.

In the case of Tidal, the following fulfills the request of Alex:
```
% git clone 'https://github.com/tidalcycles/Tidal'
% cabal build --project-file "$PWD"/Tidal/cabal.project all
% cabal exec --project-file "$PWD"/Tidal/cabal.project $SHELL
```
— And you only need the `cabal build` because `cabal exec` is happy to drop you into an inconsistent state, [as detailed elsewhere][1]. @yaxu Would you like to check this?

[1]: https://github.com/tomjaguarpaw/tilapia/issues/57

**Comment by yaxu** [comment]
@kindaro The good thing is that exiting the shell and running `cabal build` then `cabal exec $SHELL` was enough to fix things and get the new version running in ghci. This beats having to find files to edit or giving up and wiping ~/.ghc and ~/.cabal to start from scratch. 

I don't understand the problem with running `cabal exec ghci` directly by the way, it works well for me, and with no real delay.

**Comment by yaxu** [comment]
> @yaxu Would you like to check this?

It seems to have got in a bad state:

```bash
alex@olga:~/src/tidal$ cabal build --project-file cabal.project all
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - tidal-parse-0.0.1 (lib) (first run)
Preprocessing library for tidal-parse-0.0.1..
Building library for tidal-parse-0.0.1..
[2 of 2] Compiling Sound.Tidal.Parse ( src/Sound/Tidal/Parse.hs, /home/alex/src/tidal/dist-newstyle/build/x86_64-linux/ghc-8.6.5/tidal-parse-0.0.1/build/Sound/Tidal/Parse.o )
<command line>: can't load .so/.DLL for: /home/alex/src/tidal/dist-newstyle/build/x86_64-linux/ghc-8.6.5/tidal-1.7.8/build/libHStidal-1.7.8-inplace-ghc8.6.5.so (libHStidal-1.7.7-inplace-ghc8.6.5.so: cannot open shared object file: No such file or directory)
```

(In this case I don't want to load that particular `cabal.project`, as it contains `tidal-parse` which isn't generally needed and has heavy dependencies. It's just there to ensure that `tidal` and `tidal-parse` are tested together)

**Comment by jneira** [comment]
Well, once i make clear what is the user interface i want to preserve from v1, the really important thing, we could go down technical details again, 

> Essentially you like cabal env because it edits files for you. If this is what you want, then this is what you should ask for. It is not about the installation of libraries or the creation of environments — all of that is already handled by Cabal well enough.

:thinking:

It is about edit files but also installing libraries and create environment:
It edits environment config files. Create an environment is create such environment file. To edit or create that file, it needs installing libraries if they are not already.

`cabal exec shell` usage are backed by an environment file, like `cabal env`. Both installs libraries in the cabal store if they are not installed (and use the same code undernetah to do it). But the first needs project files and the second doesnt (but can use them).

Lets analyze what changes do `cabal exec` in the environment, for me it changes;

```
PATH = C:\sd\ghc-8.10.5\ansi-terminal-0.11-d29a88aeac497b45f3b742a6a6d9fefbeec35df6\bin;C:\sd\ghc-8.10.5\hspec-discover-2.8.2-c04be37fe05cc368f0a2f531080bf2aa945ded26\bin;C:\sd\ghc-8.10.5\hspec-discover-2.8.2-fa9d9508506e498d647c6c96ab7fd7b3c0c08fd6\bin;D:\dev\ws\haskell\cabal-test\dist-newstyle\build\x86_64-windows\ghc-8.10.5\cabal-test-0.1.0.0\x\cabal-test\build\cabal-test;%PATH%
GHC_ENVIRONMENT = D:\dev\ws\haskell\cabal-test\dist-newstyle\tmp\environment.-15328\.ghc.environment.x86_64-mingw32-8.10.5
```

So it could have those consequences:
* Users (or any of their tools) cant use `GHC_ENVIRONMENT` in that session or it would break the original enviroment
* If they compile any of the executables prepended in PATH directly with ghc and they put it in some directory in the original PATH, user will see the version set previously by `cabal exec` and no the fresh one (corner case? maybe, but something similar happened me with stack)

That are consequences of using the worst mutable global state we have to deal with: os environment variables. The fact everybody uses them in the unix world dont make them better.

`cabal-env` uses parameters to inject the environment in ghc plus a little bit of convention:
* If you don use a named environment it creates a ~/.ghc/ghc.version/environments/default
 * ghc reads automatically that file if it exists with no need of parameters
* If you use a named environment (and it lets you have several of them nicely identified) with `cabal-env --name myenv`
 * you have to call ghc with the env name: `ghc -package-env=myenv`

No global env vars was damaged in the making of that film 😛

**Comment by kindaro** [comment]
So, essentially `cabal-env` is an editor for `~/.ghc/…/environments/…`. Neat! But what use cases does it address that my way cannot handle? Is it all only because of your antipathy towards environment variables? As you said — everyone uses environment variables. I recall `virtualenv` from Python, `npm` from JavaScript and `opam` from OCaml from the top of my head. I am not aware of any complaints.

### The commands we already have are quite powerful:

1. `cabal exec` lets you get an environment from a package, while `cabal env` does not, short of copying all the dependencies from the Cabal file into the command line by hand.
2. This also means that it is trivial to share an environment with your friends — simply send them the Cabal package. How you would do this with `cabal env`? You cannot simply send the environment file, even if you dig it out of `~/.ghc`. You also need to tell them to install the appropriate packages, in exactly the same configuration.
3. If you want to hard-wire an environment into GHC, you can run `cabal exec`, look at the environment variable holding the path to the GHC environment file that it has set for you and copy that file into `~/.ghc/…`. This is also trivial to automate. Please write a tool that does this. It would be much simpler than `cabal-env`.

### I am not sure I can accept your specific objections:

> * Users (or any of their tools) cant use `GHC_ENVIRONMENT` in that session or it would break the original enviroment

How is it different in the case of `cabal env`? An environment variable overrides the default environment, does it not? If there is a specific bug on your mind, report and hopefully it will get fixed.

> * If they compile any of the executables prepended in PATH directly with ghc and they put it in some directory in the original PATH, user will see the version set previously by `cabal exec` and no the fresh one (corner case? maybe, but something similar happened me with stack)

Yes, `cabal exec` makes executables from your dependencies available. I am not sure I understand how this is bad and not good. You ask for a package, you get that package — libraries and executables, exactly the version you order.

### What is going on?

See:

* The commands we already have are quite powerful. `cabal env` does not add anything to this power — it is only a convenience.
* There are plenty of bugs in Cabal. Stray even a little from the _«happy path»_ and you end up in an inconsistent state. This is what needs to be worked on.
* This is an unique chance to unify the community around the core concept of Cabal — the package. We cannot hold on forever to the people who cannot get over `v1` and learn some package management. How many are there anyway? It makes no sense to add a whole command specifically for those people. Cabal is a package manager, after all!
  * And do not make it sound as if I am throwing people under the bus. I already explained how the use cases given to me by actual _(not imaginary)_ users can be handled by existing commands. If something is still unclear, ask and I shall explain again.

**Comment by kindaro** [comment]
# Alex:

You can create another file similar to your `cabal.project` but without mentioning `tidal-parse`. It can have any name. Then invoke the same commands `cabal build … && cabal exec …` on that file. This should make sure `tidal-parse` is not included in the build plan, insofar as it is not a dependency of some other package that you require.

**Comment by Mikolaj** [comment]
@kindaro: we are here to not win arguments, but to find the best design collectively and move on to do even greater things together. I appreciate your technical input a lot, but suggesting that one of Javier's doubts is based on "antipathy" and collecting a barrage of arguments that all happen to support your option doesn't look constructive enough for me. 

How about a classical challenge: would you try to swap positions with Javier for one comment and honestly strive to defend his position (not score points in his favour nor win applause for him but find rational justification for his intuitions, to the extend it exists, and while searching how they can be defended, get to understand them better)?

**Comment by kindaro** [comment]
You are right Mikolaj.

1. It would actually be cool to point to a project, package and component and say _«Cabal, make this environment available for GHC»_.
   * GHC has a feature of using named environments — why not use it?
   * The environment files are next to impossible to write by hand, but Cabal can write them for us — why not use that as well!

   What is missing is a way to connect the two.

   Is it a good tone for one program to poke into another's dot files? Maybe, instead of Cabal putting files into GHC's configuration folder, GHC should sport a command such as _«install current environment»_? Then one can say `cabal exec ghc-install-current-environment`.
   * Cabal is in the best position to create an environment file. _(Since it knows whether the desired packages are available in the store and whether they work well together.)_
   * GHC is in the best position to install an environment file. _(Since it knows what the right place to put the environment file in is.)_

2. A weakness of my plan is the uncertainty as to whether we could ever programmatically edit Cabal files. I am hyped on the news that an exact printer is coming, but an exact printer by itself is not a feature.

   Back in the days of `v1` it was easy to install a package because the model was so simple — put everything in one place and who cares if it breaks. Now you have to say what project, package and component a library should be made available for and under what Cabal flags. This can be ameliorated by making sure that every location on the file system has a default project, package and component associated with it. It would require:
   * Specifying a default set of flags for every component. _(I think this works already?)_
   * Specifying a default component for every package.
   * Specifying a default package for every project.
   * Specifying a default project for every user.

   It would be a nice touch overall because the following annoying error would go away:
   ```
   % cabal repl
   cabal: No targets given and there is no package in the current directory. Use
   the target 'all' for all packages in the project or specify packages or
   components by name or location. See 'cabal build --help' for more details on
   target options.
   ```

   Even with an exact printer it is not clear to me how to make a general enough magical editor for Cabal files. What I can see now is a command that writes a new dependency in, checks if a build plan can be constructed and undoes the edit if that fails. Together with defaulting rules as outlined above, this can make adding a dependency similar enough to installing a package in `v1` style. For example, writing a dependency in while being outside any specific project would write it into the default project, creating an illusion of installing a package in `v1` style. For a cherry on top, for the default project we can automagically call `ghc-install-current-environment`. It would also make running `cabal repl` outside of any specific project faster and more powerful, because it would pick up the default project instead of creating a fake package every time. Do we like this?

   Or maybe we can start by teaching `cabal init` and `cabal exec` to understand the option `--build-depends`, in the same way as `cabal repl`. Ideally with some nicety properties, such as `cabal init --build-depends … && cabal exec … = cabal exec --build-depends …`.

3. Or we can simply merge `cabal env` and call it a day. The code is there, it solves the problem and it is mere 492 lines of Haskell. The changes required to make the way of `cabal exec` work well enough are many and non-trivial — who is going to do this work?

**Comment by Mikolaj** [comment]
That is masterful. I bow to the ground.

**Comment by jneira** [comment]
Wow, amazing analysis from several sides, being able to do that is the key of a good engineering excellence.
Not sure if i can add anymore sensible after that, to be honest. Dont worry, i think the tone has been correct and refreshing.

**Comment by kindaro** [comment]
Thanks folks. I appreciate your kindness more than words can say.

For what it is worth, I want to have defaulting even if `cabal env` goes in. I am going to open an issue of its own for that.

**Comment by singpolyma** [comment]
I have read a lot of this thread, and I'm a bit confused.  It seems like `cabal install --lib` (if it worked) I would expect to be roughly equivalent to `cabal v1-install`, whereas `cabal env` and `cabal exec` seem like they want to build a project-specific environment, is that right?

**Comment by singpolyma** [comment]
@jneira and just so I'm clear, what is a "project"?  A `.cabal` file?

**Comment by jneira** [comment]
I posted something like a demo of `cabal-env` used outside of a cabal project in this coment: https://github.com/haskell/cabal/issues/6481#issuecomment-854182128

**Comment by Mikolaj** [comment]
I *think* the only way you can use `world` is via `cabal install world`. So if you don't, your workflow should not be affected.

Citing some things removed in that PR:

```
     -- | A special virtual package that refers to the collection of packages
     -- recorded in the world file that the user specifically installed.
     --
     -- > cabal install world

-- To rebuild/upgrade the packages in world (e.g. when updating the compiler)
-- use
-- # cabal install world
```

And the changelog of this PR:

```
synopsis:  Remove World file functionality
packages: cabal-install
issues: #6767
prs: #7746
description: {
In v1-install, 'world' was used to trace what packages have been
installed, and re-install everything that is listed in it on-demand. However, in
v2-install, this is no longer needed, and outdated.
Additionally, 'world' code-path is probably not up-to-date, remove it instead of
having partial features.

- Don't generate `world` file in `~/.cabal` when `v1-install` is executed.

- Don't ever read `world` from `~/.cabal`.

- Remove meta-target `world` from `v1-install`.
}
```

**Comment by tomsmeding** [comment]
(This issue is linked from the `cabal install --help` output for the `--lib` flag.)

The semantics of `cabal install --lib` continues to confuse people: e.g. in [this irc discussion](https://ircbrowse.tomsmeding.com/day/lchaskell/2024/02/08?id=1209716#trid1209716) (links to [this paste](https://paste.debian.net/plain/1306714)), before reading on towards the resolution of the problem, and trying to forget the context of this issue, I challenge you to find out what the problem is for this user.

I get that there are many colourable panels on the bikeshed that is `cabal env`, and even many real engineering choices and challenges, but can we please, at least, have some warning if `cabal install --lib` creates a new environment file? Perhaps the warning should not be displayed (or should not be very loud) if an environment file already exists, to acknowledge the small (?) set of people who are actually _using_ this functionality, but I suspect that the vast majority of people who run `cabal install --lib` were _not_ intending to create an environment file, with all the action-at-a-distance consequences that entails.

Currently there is _no output at all_ when you run `cabal install --lib` that indicates that something potentially dangerous happened. Can we change that?

**Comment by ulysses4ever** [comment]
Great idea, I think. I'd open a separate issue though.
