### ISSUE TITLE
Some tests failing with GHC 9.0.2

### ISSUE THREAD

**Issue by andreabedini** [haskell/cabal#7987]
From https://github.com/haskell/cabal/pull/7952#issuecomment-1038742571

The following tests fail on GHC 9.0.2 (but not GHC 9.0.1) on both Linux and Mac

- PackageTests/Backpack/Includes2/setup-external.test.hs
- PackageTests/Backpack/Includes3/setup-external-ok.test.hs
- PackageTests/Backpack/Includes2/setup-per-component.test.hs

**Comment by wz1000** [comment]
Might be related to https://gitlab.haskell.org/ghc/ghc/-/issues/20903

**Comment by Kleidukos** [comment]
No idea on my end :(

**Comment by Mikolaj** [comment]
Thanks. 

@hasufell: I guess you had no reports of 9.0.2 having missing/broken haddocks in the Linux package, as distributed by ghcup? Probably not the case, but just checking.

**Comment by wz1000** [comment]
Some 9.0.2 distributions (all the hadrian generated ones in fact - which would be the fedora one IIRC) also don't have haddocks.

**Comment by Mikolaj** [comment]
@wz1000: thank you. So nothing to worry about. It'll get fixed in 9.0.3, if it gets released.

@andreabedini: how would you mark the failures as expected so that we remember to unmark then when 9.0.3 is out? Perhaps we should leave this ticket open to remember? Change the ticket title mentioning 9.0.3 and adding lots of exclamation marks?

**Comment by andreabedini** [comment]
> @andreabedini: how would you mark the failures as expected so that we remember to unmark then when 9.0.3 is out? Perhaps we should leave this ticket open to remember? Change the ticket title mentioning 9.0.3 and adding lots of exclamation marks?

Given all three failures seem to be related to haddock, I'd say we can use this ticket, either as it as it is or changing the title. The ticket is also mentioned in the workflow so we can be reminded from there too.

**Comment by andreabedini** [comment]
This seems to appen on GHC 9.2 too https://github.com/haskell/cabal/runs/5298365693?check_suite_focus=true#step:11:1995

**Comment by ulysses4ever** [comment]
Unfortunately, hasn't got fixed in [9.2.2](https://github.com/haskell/cabal/runs/7050959899?check_suite_focus=true) or [9.2.3](https://github.com/haskell/cabal/runs/7054107944?check_suite_focus=true).

**Comment by ulysses4ever** [comment]
One more observation: after successfully checking Haddocks in `base` (via `--show-iface`, as suggested in https://gitlab.haskell.org/ghc/ghc/-/issues/20903), I can confirm that this failure still reproduces on GHC 9.2.3 (and 9.0.2, as delivered by GHCup in Linux x86_64). So we need another guess at what happens here...

**Comment by roconnor-blockstream** [comment]
Is there a workaround to avoid this crash, beyond simply not building documentation?

**Comment by Mikolaj** [comment]
@roconnor-blockstream: I don't think we know of any. What's the scenario in which you get an error of this kind?

**Comment by roconnor-blockstream** [comment]
Building my [project](https://github.com/ElementsProject/simplicity) under GHC 9.2 (and 9.4).  More specifically the `runhaskell Setup.lhs haddock` command fails in the end with the error

    haddock: internal error: haddock:iface
    CallStack (from HasCallStack):
      error, called at utils/haddock/haddock-api/src/Haddock/Interface.hs:179:16 in main:Haddock.Interface

My project makes use of Backpack.

**Comment by Mikolaj** [comment]
Thank you for the details. Where is that `Setup.lhs` file? I can only see `Setup.hs`. Does it fail like that with `cabal haddock` as well?

**Comment by roconnor-blockstream** [comment]
Sorry.  I should have written `Setup.hs`.

`cabal haddock` does appear to work.

**Comment by Mikolaj** [comment]
OK, that's an important hint for somebody willing to dig into cabal and haddock code. And the `Setup.hs` is not anything custom, so the problem is probably not related to the dreaded Custom Setups. I guess the place to start would be to run with verbosity -v2 and compare the arguments passed to `haddock` with `runhaskell Setup.lh haddock` and `cabal haddock` in your project.

**Comment by roconnor-blockstream** [comment]
Using `runhaskell Setup.hs haddock` executes

    /nix/store/4zpfpnwflsrpf1lmnnx9jkdypzpz2b1j-ghc-9.2.3-with-packages/bin/haddock '@dist/doc/html/Simplicity/haddock-response287381-7.txt'

while using `cabal haddock`

    /nix/store/4zpfpnwflsrpf1lmnnx9jkdypzpz2b1j-ghc-9.2.3-with-packages/bin/haddock '@/home/roconnor/Simplicity/dist-newstyle/build/x86_64-linux/ghc-9.2.3/Simplicity-0.0.0/l/Simplicity-Indef/doc/html/Simplicity/haddock-response286953-1.txt'

But these response files are cleaned up right away so I cannot view them.  Is there a flag to keep them?

**Comment by Mikolaj** [comment]
Ouch, that's not as helpful as I imagined. I can't find any such option either in `haddock` or in `cabal haddock` (in case the file is deleted by cabal). I suppose hacks such as copyfs may do the trick: https://unix.stackexchange.com/questions/71067/view-temporary-files-which-exist-for-milliseconds

**Comment by jneira** [comment]
such flag (--keep-temp-files?) would be really useful to trace problems like this

**Comment by roconnor-blockstream** [comment]
the `--keep-temp-files` flag works with `runhaskell Setup.hs`, however I haven't figured out where to place `haddock-keep-temp-files: True` to make it work with `cabal haddock`.

One thing to observe is that `runhaskell Setup.hs` builds the haddock for each different library in the same place, clobbering the previous library's documentation.  This has always been a problem for my backpack builds.  The `cabal haddock` command seems to properly build each component in a separate directory.

**Comment by Mikolaj** [comment]
> One thing to observe is that `runhaskell Setup.hs` builds the haddock for each different library in the same place

Oh, that rings a bell. There was a realated (partial?) fix recently: #7827. Also related: https://github.com/haskell/haddock/issues/1363 amd https://github.com/haskell/haddock/pull/1379. But OTOH, I seem to remember support for multiple (public?) libraries was supposed to be added only at the `cabal haddock` level, not Setup level. Do I remember right @fgaz?

**Comment by Mikolaj** [comment]
BTW, is https://github.com/haskell/haddock/issues/1363 fixed? @roconnor-blockstream seems to have a reasonable experience with `cabal haddock` and a backpack project. Is anything else missing? @Kleidukos, @coot, @fgaz? I guess Hackage may not yet be ready to display such haddocks?

**Comment by roconnor-blockstream** [comment]
I wouldn't say I have a reasonable experience.  I make due with making a manual index.html, and even then, all the problems in https://github.com/haskell/haddock/issues/1363 persist.  I just assumed they would be fixed one day, but maybe the right answer is to use `cabal haddock`.  I haven't really examined the output yet.

**Comment by roconnor-blockstream** [comment]
FWIW, I no longer get these `haddock: internal error: haddock:iface` errors when using GHC 9.8.2 at least.

**Comment by Mikolaj** [comment]
Wonderful. 

Anything else left to be done in this ticket? Do the tests from the ticket description pass now?
